baseURL: https://blog.jrasm.com/
languageCode: en-us
title: My Two Bytes

enableRobotsTXT: true
googleAnalytics: G-S7JQK5D2RV

theme: PaperMod

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 10
    - identifier: tutorials
      name: Tutorials
      url: /tutorials
      weight: 20
    - identifier: notes
      name: Notes
      url: /notes
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  env: production
  title: My Two Bytes
  description: My two bytes about software, programming, and technology.

  defaultTheme: dark
  disableThemeToggle: true

  showShareButtons: false
  showReadingTime: true
  showBreadCrumbs: true
  showPostNavLinks: true
  showCodeCopyButtons: true

  disableScrollToTop: true
  comments: false

  cover:
    hiddenInList: true

  label:
    text: 'My Two Bytes'

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/jrasm91'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/2833217/jrasm91'
    - name: github
      url: 'https://github.com/jrasm91'

  homeInfoParams:
    title: Hello ğŸ‘‹!
    content: >
      I'm Jason, a ğŸ’» fullstack developer, ğŸ‘¨ husband, and ğŸ‘¨â€ğŸ‘©â€ğŸ‘§ proud father. Welcome to "My Two Bytes", a small blog built with [Hugo](https://gohugo.io).

outputs:
  home:
    - HTML
    - RSS
    - JSON
