baseURL: https://blog.jrasm.com/
languageCode: en-us
title: My Two Bytes

enableRobotsTXT: true
googleAnalytics: UA-101199977-2

module:
  imports:
    - path: "github.com/adityatelange/hugo-PaperMod"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

params:
  env: production
  title: My Two Bytes
  description: My two bytes about software, programming, and technology.

  defaultTheme: dark
  disableThemeToggle: true

  showShareButtons: false
  showReadingTime: true
  showBreadCrumbs: true
  showPostNavLinks: true

  disableScrollToTop: true
  comments: false

  cover:
    hiddenInList: true

  label:
    text: "My Two Bytes"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/jrasm91"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/2833217/jrasm91"
    - name: github
      url: "https://github.com/jrasm91"

  homeInfoParams:
    title: Hello ğŸ‘‹!
    content: >
      I'm Jason, a ğŸ’» fullstack developer, ğŸ‘¨ husband, and ğŸ‘¨â€ğŸ‘©â€ğŸ‘§ proud father. Welcome to "My Two Bytes", a small blog build with [Hugo](https://gohugo.io). To learn more about why I built this site, see [My Tiny Projects](/posts/my-tiny-projects).

output:
  home:
    - JSON
    - RSS
